apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry-deployment
  namespace: beta-app
  labels:
    app: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: 306472407007.dkr.ecr.ap-south-1.amazonaws.com/ibs-skillset-happystays/service-registry:dee265a
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8761