apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry-deployment
  labels:
    app: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: docker.io/library/service-registry:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8761