server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  instance:
    hostname: service-registry
    health-check-url-path: /actuator/health
  client:
    registerWithEureka: false
    fetchRegistry: false

endpoints:
  shutdown:
    enabled: true