---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: beta-app
spec:
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app.kubernetes.io/name: service-registry